appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 85LlAFowWGY/S5rV3K1re/Al7qnqzMykw7TM4NGYNFmauU2FgWR8aCHfbTZVVaU+uwSQJjsbi8wgzLtVtWw9hltyui0GzFxu8m8ptyKaF4HqSt+udm3ytyaSZyGBLmothJ5CKnyFj9eLbm2+9BrGGdLK1KLA6729G4QCQlfxHIDMpnak2VmdfDZjdVtfHFPfxJPcDfe4DtnLTzela4coVMAa1kbHFWQHBBurcl6aaGHvisYvtV+j8EhawMIU2cqc2NM/PagCGO3AbVK/uLffRYqUuD85ho7MtC7MefiEGMp+0Kw8NQ0YfgKXKa0oqcuU3XwuZ32f5KQYKiKdwBsUgXE57seWG9vu6vEUDdGYLEnOjEp+xa2m9ezmg6FkORyAiJose6WEOXp01EUxzz/l+3EPjmTZB7Qk+lf3rMVjj85CnyxZ4JE3OhU+Rnk2gtUn+B+HUpDt5yiWPXTgAiT5L/hI5emiFa1wf5UybX+sPI3ualTKqn1YYJWS7Afufs4GmA6FAeMRn5PfDsWlmKscogtexomzyTGZm9lRnIdCm4l+Chi3uGGK5Vt3zZacpUXMh5/AZDMnBwqle+zzQCKoAK1m0Tkz4NwIN6z3b0Vaar7cTxdrcL6lNjfOgF/KM+a8Gh2fFHcS6nMYIfc07MzD6jj+cJawvLcAEW39YWQjzaw=}
provider:
  win: azure
